name: docker

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install decentraland
        run: npm i -g decentraland@latest
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: build
        run: npm run test
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: sdk-ws
          tags: ${{ github.sha }} next
          dockerfiles: |
            ./Dockerfile
      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push To quay.io
        if: github.ref == 'refs/heads/main'
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/decentraland
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Print image url
        if: github.ref == 'refs/heads/main'
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

      - name: Trigger deployment
        id: deploy
        if: github.ref == 'refs/heads/main'
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: "${{ steps.push-to-quay.outputs.registry-path }}"
          serviceName: sdk-ws
          env: dev
          token: ${{ secrets.GITHUB_TOKEN }}